// For article actions
export const GET_USER_ARTICLES_SUCCESS="GET_USER_ARTICLES_SUCCESS"
export const SAVE_ARTICLE_SUCCESS="SAVE_ARTICLE_SUCCESS"
export const SAVE_ARTICLE_ERROR="SAVE_ARTICLE_ERROR"
export const GET_ALL_ARTICLES_SUCCESS="GET_ALL_ARTICLES_SUCCESS"
export const GET_ALL_ARTICLES_ERROR="GET_ALL_ARTICLES_ERROR"
// For auth actions
export const LOADING="LOADING"
export const LOADED="LOADED"
export const AUTH_TOKEN_ERROR="AUTH_TOKEN_ERROR"
export const REGISTER_SUCCESS="REGISTER_SUCCESS"
export const LOGIN_SUCCESS="LOGIN_SUCCESS"
export const REGISTER_FAIL="REGISTER_FAIL"
export const LOGIN_FAIL="LOGIN_FAIL"
export const LOGOUT_SUCCESS="LOGOUT_SUCCESS"
export const REFRESH_AUTH_SUCCESS="REFRESH_AUTH_SUCCESS"
// For error actions 
export const GET_ERRORS="GET_ERRORS"
export const CLEAR_ERRORS="CLEAR_ERRORS"